import { test, expect } from '@playwright/test';
import { UserLoginPage } from '../pages/UserLoginPage';

// Auto-generated by the Generator agent from test plan: user-login-1789437708140
test.describe('User Login', () => {
  test('a registered user — they submit valid credentials → they land on the dashboard', { tag: ['@auth', '@smoke', '@happy-path'] }, async ({ page }) => {
    const pageObject = new UserLoginPage(page);
    await pageObject.goto('/');
    await pageObject.fillEmailField('a registered user');
    await pageObject.fillPasswordField('they submit valid credentials');
    await pageObject.clickSubmitButton();
    // expect: they land on the dashboard
    // TODO: replace with a real assertion for this feature's UI.
    await expect(page).toHaveURL(/.+/);
  });

  test('a registered user — they submit an incorrect password → an inline error "Invalid email or password" is shown', { tag: ['@auth', '@smoke', '@negative'] }, async ({ page }) => {
    const pageObject = new UserLoginPage(page);
    await pageObject.goto('/');
    await pageObject.fillEmailField('a registered user');
    await pageObject.fillPasswordField('they submit an incorrect password');
    await pageObject.clickSubmitButton();
    // expect: an inline error "Invalid email or password" is shown
    // TODO: replace with a real assertion for this feature's UI.
    await expect(page).toHaveURL(/.+/);
  });

  test('an empty email field — the user submits the form → a validation message is shown and no request is sent', { tag: ['@auth', '@smoke', '@happy-path'] }, async ({ page }) => {
    const pageObject = new UserLoginPage(page);
    await pageObject.goto('/');
    await pageObject.fillPasswordField('the user submits the form');
    await pageObject.clickSubmitButton();
    // expect: a validation message is shown and no request is sent
    // TODO: replace with a real assertion for this feature's UI.
    await expect(page).toHaveURL(/.+/);
  });

  test('a locked account — the user submits valid credentials → an account-locked message is shown', { tag: ['@auth', '@smoke', '@negative'] }, async ({ page }) => {
    const pageObject = new UserLoginPage(page);
    await pageObject.goto('/');
    await pageObject.fillEmailField('a locked account');
    await pageObject.fillPasswordField('the user submits valid credentials');
    await pageObject.clickSubmitButton();
    // expect: an account-locked message is shown
    // TODO: replace with a real assertion for this feature's UI.
    await expect(page).toHaveURL(/.+/);
  });
});
